[theme]
base = "light"
primaryColor = "#465CFF"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
